# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('girls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Зарезервированный заказ',
                'verbose_name_plural': 'Зарезервированные заказы',
            },
        ),
        migrations.AlterUniqueTogether(
            name='wish',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='wish',
            name='gift',
        ),
        migrations.RemoveField(
            model_name='wish',
            name='girl',
        ),
        migrations.AlterModelOptions(
            name='gifts',
            options={'verbose_name': 'Желание', 'verbose_name_plural': 'Желания'},
        ),
        migrations.AlterModelOptions(
            name='girls',
            options={'verbose_name': 'Довочка', 'verbose_name_plural': 'Девченки'},
        ),
        migrations.AlterField(
            model_name='gifts',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Желание'),
        ),
        migrations.AlterField(
            model_name='girls',
            name='code',
            field=models.CharField(default='lpm', max_length=3, verbose_name='Уникальный код'),
        ),
        migrations.AlterField(
            model_name='girls',
            name='fio',
            field=models.CharField(max_length=250, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='girls',
            name='flour',
            field=models.SmallIntegerField(verbose_name='Этаж'),
        ),
        migrations.DeleteModel(
            name='Wish',
        ),
        migrations.AddField(
            model_name='wishes',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='girls.Gifts'),
        ),
        migrations.AddField(
            model_name='wishes',
            name='girl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='girls.Girls'),
        ),
        migrations.AlterUniqueTogether(
            name='wishes',
            unique_together=set([('girl', 'gift')]),
        ),
    ]
