# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import random
import string


class Migration(migrations.Migration):

    dependencies = [
        ('girls', '0011_remove_girls_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='girls',
            name='code',
            field=models.CharField(db_index=True, default=''.join(random.sample(string.ascii_lowercase, 3)), max_length=3, verbose_name='Уникальный код'),
        ),
    ]
