# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girls', '0015_auto_20170306_0646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishes',
            name='done',
        ),
        migrations.AddField(
            model_name='wishes',
            name='status',
            field=models.BooleanField(choices=[(0, 'Не готово'), (1, 'Готово')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='girls',
            name='code',
            field=models.CharField(db_index=True, default='ari', max_length=3, verbose_name='Уникальный код'),
        ),
    ]
