# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('girls', '0016_auto_20170306_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girls',
            name='code',
            field=models.CharField(db_index=True, default='aps', max_length=3, verbose_name='Уникальный код'),
        ),
        migrations.AlterField(
            model_name='wishes',
            name='gift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift', to='girls.Gifts'),
        ),
        migrations.AlterField(
            model_name='wishes',
            name='girl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='girl', to='girls.Girls'),
        ),
        migrations.AlterField(
            model_name='wishes',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
