# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('girls', '0017_auto_20170306_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='girls',
            name='code',
            field=models.CharField(db_index=True, default='otl', max_length=3, verbose_name='Уникальный код'),
        ),
    ]
